web/auth.py
from flask import Blueprint,render_template,request,flash,redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash
from . import db
from flask_login import login_user, login_required, logout_user, current_user
    
auth = Blueprint('auth', __name__)

@auth.route('/sign-in',methods=['GET','POST'])
def sign_in():
    if request.method == 'POST':
        id = request.form.get('login_id')
        password1 = request.form.get('login_pw')

        # search User in database & compare password
        user = User.query.filter_by(id=id).first()
        if user:
            if check_password_hash(user.password, password1):
                flash('로그인 완료', category='success')
                login_user(user, remember=True)
                return redirect(url_for('view.main'))
            else: 
                flash('비밀번호가 다릅니다.', category='error')
        else:
            flash('해당 아이디 정보가 없습니다.', category='error')

    return render_template('login.html')


@auth.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('view.home'))



@auth.route('/sign-up',methods=['GET','POST'])
def sign_up():
    if request.method == 'POST':
        # form - input의 name 속성을 기준으로 가져오기
        nickname = request.form.get('gaib_nick')
        email = request.form.get('email')
        gaib_id = request.form.get('gaib_id') # 이름 수정
        gaib_pw = request.form.get('gaib_pw') # 추가
        phone = request.form.get('phone') # 이름 수정
        
        # 중복 이메일 검사
        existing_user_email = User.query.filter_by(email=email).first()
        if existing_user_email:
            flash('이미 사용 중인 이메일입니다.', category='error')
            return render_template('gaib.html')

        # 중복 아이디 검사
        existing_user_id = User.query.filter_by(id=gaib_id).first()
        if existing_user_id:
            flash('이미 사용 중인 아이디입니다.', category='error')
            return render_template('gaib.html')

        # 중복 전화번호 검사
        existing_user_phone = User.query.filter_by(phone=phone).first()
        if existing_user_phone:
            flash('이미 사용 중인 전화번호입니다.', category='error')
            return render_template('gaib.html')
        
        # 중복 전화번호 검사
        existing_user_nick = User.query.filter_by(nickname=nickname).first()
        if existing_user_nick:
            flash('이미 사용 중인 닉네임 입니다.', category='error')
            return render_template('gaib.html')
        
        new_user = User(id = gaib_id ,
                        email=email, 
                        nickname=nickname, 
                        password=generate_password_hash(gaib_pw,method='sha256'),
                        phone = phone)
        db.session.add(new_user)
        db.session.commit()
        

        flash('회원가입 완료',category='success')
        return redirect(url_for('auth.sign_in'))
    return render_template('gaib.html')

web/views.py
import sys
import os
# 현재 프로젝트 디렉터리를 Python 모듈 검색 경로에 추가
sys.path.append(os.path.dirname(os.path.abspath(__file__)))

from flask import Blueprint, session, jsonify, send_from_directory
from flask import render_template
from flask_login import login_required, current_user
import translate as ts
from flask import request, flash, redirect, url_for
import test_ai as ai
import ai_fuction as af
from . import db
from werkzeug.security import check_password_hash, generate_password_hash
from werkzeug.utils import secure_filename
from .models import User, SearchHistory

translate_json_path = 'abstract-plane-396801-904742608cb2.json'

views = Blueprint('view', __name__)


@views.route("/")
def home():
    return render_template('login.html')


@views.route('/main/mypage', methods=['GET', 'POST'])
def mypage()-> object:
    if request.method == 'POST':
        # HTML 폼에서 제공된 데이터 가져오기
        nickname = request.form.get('gaib_nick')
        current_password = request.form.get('now_pw')
        new_password = request.form.get('gaib_pw')
        confirm_password = request.form.get('gaib_pw1')
        email = request.form.get('email')
        phone = request.form.get('phone')
        user = User.query.filter_by(id=current_user.id).first()
        # 예제: 닉네임 및 이메일 유효성 검사
        if not nickname or not email:
            flash("닉네임 및 이메일은 필수 입력 항목입니다.")
            return redirect(url_for('view.mypage'))

        if not check_password_hash(user.password, current_password):
            flash("비밀번호가 다릅니다.")
            return redirect(url_for('view.mypage'))

        # 새로운 비밀번호 확인
        if new_password != confirm_password:
            flash("비밀번호가 일치하지 않습니다.")
            return redirect(url_for('view.mypage'))

        # 데이터베이스 업데이트
        current_user.nickname = nickname
        if new_password:  # 새 비밀번호가 있을 경우만 업데이트
            current_user.password = generate_password_hash(
                new_password, method='sha256')
        current_user.email = email
        current_user.phone = phone

        db.session.commit()

        flash("정보가 성공적으로 수정되었습니다.")
        return redirect(url_for('view.mypage'))

    user_nickname = current_user.nickname
    user_email = current_user.email
    user_id = current_user.id
    user_phone = current_user.phone
    search_history = SearchHistory.query.filter_by(user_id=current_user.id).order_by(
        SearchHistory.timestamp.desc()).limit(15).all()
    return render_template('mypage.html',user_id=user_id,user_email=user_email,user_phone=user_phone,user_nickname=user_nickname, search_history=search_history)


@views.route('/delete-history/<int:record_id>', methods=['DELETE'])
@login_required
def delete_history(record_id):
    record = SearchHistory.query.get(record_id)
    if not record:
        return jsonify({"message": "Record not found!"}), 404
    if record.user_id != current_user.id:
        return jsonify({"message": "Unauthorized!"}), 403

    db.session.delete(record)
    db.session.commit()
    return jsonify({"message": "Record deleted successfully!"}), 200


@views.route('/view-history-detail/<timestamp>')
def view_history_detail(timestamp):
    history_record = db.session.query(
        SearchHistory).filter_by(timestamp=timestamp).first()
    if not history_record:
        return "No record found for the given timestamp", 404
    history_record_img_path = history_record.image_path
    return render_template('history_detail.html',record=history_record,img_path=history_record_img_path)


@views.route('/main', methods=['GET', 'POST'])
@login_required
def main():
    user_nickname = current_user.nickname
    translated_text = ""
    if request.method == 'POST':
        text_to_translate = request.form.get('trans_text')
        if text_to_translate is None or text_to_translate.strip() == "":
            flash('텍스트를 입력해주세요.', category='error')
        else:
            if text_to_translate:
                new_search = SearchHistory(user_id=current_user.id,search_text=text_to_translate)
                db.session.add(new_search)
                db.session.commit()
            tr = ts.GoogleCloudTranslator(translate_json_path)
            translated_text = tr.translate(text_to_translate, 'en')['tgt_text']
            session['translated_text'] = translated_text
            session['text_to_translate'] = text_to_translate
            return redirect(url_for('view.result',
                                    search=translated_text))
    return render_template('main.html',user_nickname=user_nickname,ranslated_text=translated_text)


@views.route('/result')
@login_required
def result():
    search_term = request.args.get('search', default="")
    if not search_term:
        # 검색어가 쿼리 파라미터로 제공되지 않았다면 메인 페이지로 리디렉션
        return redirect(url_for('view.main'))
    return render_template('result.html', search_term=search_term)


MEDIA_FOLDER = os.path.join('web/static/media')


@views.route('/get_prediction')
@login_required
def get_prediction():
    """_summary_
        이미지를 예측하는 함수
    Returns:
        _type_: json 파일
    """
    if not os.path.exists(MEDIA_FOLDER):  # Check if media directory exists
        os.makedirs(MEDIA_FOLDER)  # If not, create it\

    search_term = request.args.get('search', default="")

    # 이미 예측된 값이 세션에 있으면 해당 값을 반환
    if 'predicted_data' in session and session['search_term'] == search_term:
        return jsonify(session['predicted_data'])

    # 예측 진행
    translated_text = search_term
    img_cat, img_data_raw = af.predicts(ai.gan_model(translated_text))
    # raw 이미지 데이터를 실제 파일로 저장
    filename = secure_filename(f"{search_term}.jpeg")
    image_path = os.path.join(MEDIA_FOLDER, filename)

    with open(image_path, 'wb') as f:
        f.write(img_data_raw)

    # 이미지 경로를 DB에 저장
    text_to_translate = session.get('text_to_translate')
    history = SearchHistory.query.filter_by(
        search_text=text_to_translate).first()
    if history:
        history.image_path = filename
        db.session.commit()

    result = {
        'translated_text': translated_text,
        'img_cat': img_cat,
        'img_src': url_for('static', filename='media/' + filename)
    }
    # 예측 결과와 검색어를 세션에 저장
    session['predicted_data'] = result
    session['search_term'] = search_term

    return jsonify(result)


@views.route('/media/<filename>')
def media_serve(filename):
    return send_from_directory(MEDIA_FOLDER, filename)

web/templates/gaib.html
<!DOCTYPE html>
<html lang="ko"> <!-- 코드언어 표시 == 웹 표준지침 준수 -->
<head>
<meta charset="UTF-8">
<title>올리브 회원가입</title> 
<link rel="stylesheet" href={{url_for('static',filename='css/gaib.css')}}>
<script src="static/js/gaib.js"></script>
</head>
<body>
    <form name="join_form",action="/sign-up" method="POST" onsubmit="return joinform_check();">
        <div class="wrap">
            <div class="gaib">
                <img src="./static/logo.png" alt="logo">
                
                <div class="gaib_nick">
                    <h5>닉네임</h5>
                    <input type="text" name="gaib_nick" id="gaib_nick" maxlength="20" placeholder="닉네임을 입력하세요">
                </div>
                <div class="gaib_id">
                    <h5>아이디</h5>
                    <input type="text" name="gaib_id" id="gaib_id" maxlength="20" placeholder="아이디를 입력하세요">
                </div>
                <div class="gaib_pw">
                    <h5>비밀번호</h5>
                    <input type="password" name="gaib_pw" id="gaib_pw"  maxlength="20" placeholder="비밀번호를 입력하세요">
                </div>
                <div class="gaib_pw1">
                    <h5>비밀번호 재확인</h5>
                    <input type="password" name="gaib_pw1" id="gaib_pw1" maxlength="20" placeholder="비밀번호를 재입력하세요">
                </div>

                <div class="email">
                    <h5>이메일</h5>
                    <input type="text" name="email" id="email" maxlength="20" class="check" placeholder="이메일을 입력하세요">
                    
                </div>

                <div class="phone">
                    <h5>전화번호</h5>
                    <input type="text" name="phone" id="phone" class="check" placeholder="-를 제외하고 입력하세요">
                    
                </div>
    
                <div class="membergaib">
                    <input type="submit" value="가입하기">
                </div>
                    {% if messages %}
                        {% for category, message in messages %}
                            {%if category == 'error'%}
                                <div class="alert alert-{{ category }}">{{ message }}</div>
                            {% endif %}
                        {% endfor %}
                    {% endif %}
            </div>
        </div>
    </form>
</body>
</html>

web/templates/history_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>결과 페이지</title>
    <link rel="stylesheet" href={{url_for('static',filename='css/history_detail.css')}}>
</head>
<body>
    <a href="{{ url_for('view.main') }}">
        <img src="{{ url_for('static', filename='logo.png') }}" alt="logo">
    </a>

    <div id="results" >
        <h3>인공지능 결과</h3>
        <p>검색 내용: {{ record.search_text }}</p>
        <p>결과: {{ record.img_cat }}</p>
        <img id="imageResult" src= "{{ url_for('static', filename= 'media/'+img_path) }}" alt="이미지 결과">
        <button onclick="document.location.href='/main/mypage'" id="backToSearchButton">검색기록 페이지로 돌아가기</button>
    </div>
</body>
</html>

web/templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>All-Leave_login</title>
    <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500;700&display=swap" rel="stylesheet">
    <script src="https://kit.fontawesome.com/53a8c415f1.js" crossorigin="anonymous"></script>
    <link rel="stylesheet" href={{url_for('static',filename='css/login.css')}}>
    <script src="static/js/login.js"></script>
</head>
<body>
    <form name="join_form" action="{{ url_for('auth.sign_in') }}" method="POST" onsubmit="return joinform_check();">
        <div class="wrap">
        <div class="login">
            <img src="./static/logo.png" alt="logo">
            
            <div class="login_id">
                <h4>아이디</h4>
                <input type="text" name="login_id" id="login_id" placeholder="아이디를 입력하세요">
            </div>
            <div class="login_pw">
                <h4>비밀번호</h4>
                <input type="password" name="login_pw" id="login_pw" placeholder="비밀번호를 입력하세요">
            </div>

            <div class="submit-login">
                <button type="submit">로그인</button>
                {% if messages %}
                    {% for category, message in messages %}
                        {%if category == 'error'%}
                            <div class="alert alert-{{ category }}">{{ message }}</div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            </div>
            <div class="submit-gaib">
                <button type="button" onclick="document.location.href='sign-up'">회원가입</button>
            </div>

        </div>
    </div>
</form>
</body>
</html>

web/templates/main.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>검색 페이지</title>
    <link rel="stylesheet" href={{url_for('static',filename='css/main.css')}}>
</head>
<body>
    <div class="top">
        <div class="top_menu">
            <a>{{ user_nickname }}</a>
            <a href="{{ url_for('view.mypage') }}">MyPage</a>
            <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>
    </div>
    
    <section>
        <form action="/main" method="POST" id="searchForm"  onsubmit="return checkInput();">
            <div class="main">
                <img src="./static/logo.png" alt="logo">
                <div class="searchBox">
                    <input type="text" name="trans_text" id="trans_text" class="query" value="" >
                    <button type="submit" class="icons">
                    <img src="./static/search.png" alt="search">
                </div>
            </div>
        </form>
    </section>

    <script src="static/js/main.js"></script>
</body>
</html>

web/templates/mypage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href={{url_for('static',filename='css/mypage.css')}}>
    <title>Document</title>
</head>
<body>
        <div class="image-container">
            <a href="{{ url_for('view.main') }}">
                <img src="{{ url_for('static', filename='logo.png') }}" alt="logo">
            </a>
        </div>
        <div class="top_menu">
            <a >{{ user_nickname }}</a>
            <a href="{{ url_for('auth.logout') }}">Logout</a>
        </div>
        <div class="my-container">
            <h3 class="link-info">Edit Info</h3>  
            <h1 class="link-my"><b>My page</b></h1>        
            <h3 class="link-search">Search History</h3>
         </div>

         <div class="page1" id="pageContent-my">
                <div class="gaib_nick">
                    <h5>닉네임</h5>
                    <p>{{ user_nickname }}</p> <!-- 사용자 닉네임 출력 -->
                </div>
                <div class="gaib_id">
                    <h5>아이디</h5>
                    <p>{{ user_id }}</p> <!-- 사용자 아이디 출력 -->
                </div>
                <div class="email">
                    <h5>이메일</h5>
                    <p>{{ user_email }}</p> <!-- 사용자 이메일 출력 -->
                </div>
                <div class="phone">
                    <h5>전화번호</h5>
                    <p>{{ user_phone }}</p> <!-- 사용자 전화번호 출력 -->
                </div>

         </div>
         <div class="separator"></div>
         <form action="{{ url_for('view.mypage') }}" method="post">
            <div class="page" id="pageContent-info">
                <div class="gaib_nick">
                    <h5>닉네임</h5>
                    <input type="text" name="gaib_nick" id="gaib_nick"  maxlength="20" placeholder="닉네임을 입력하세요">
                </div>
                <div class="now_pw">
                    <h5>현재 비밀번호</h5>
                    <input type="password" name="now_pw" id="now_pw"  maxlength="20" placeholder="현재 비밀번호를 입력하세요">
                </div>
                <div class="gaib_pw">
                    <h5>새로운 비밀번호</h5>
                    <input type="password" name="gaib_pw" id="gaib_pw"  maxlength="20" placeholder="새로운 비밀번호를 입력하세요">
                </div>
                <div class="gaib_pw1">
                    <h5>비밀번호 재확인</h5>
                    <input type="password" name="gaib_pw1" id="gaib_pw1" maxlength="20" placeholder="비밀번호를 재입력하세요">
                </div>

                <div class="email">
                    <h5>이메일</h5>
                    <input type="text" name="email" id="email" maxlength="20" class="check" placeholder="이메일을 입력하세요">   
                </div>

                <div class="phone">
                    <h5>전화번호</h5>
                    <input type="text" name="phone" id="phone" class="check" placeholder="-를 제외하고 입력하세요">
                </div>
                {% with messages = get_flashed_messages() %}
                    {% if messages %}
                        <div class="flash-messages">
                            {% for message in messages %}
                                <p>{{ message }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                {% endwith %}
                <div class="membergaib">
                    <button type="submit" onclick="joinform_check();">수정하기</button>
                </div>
            </div>
        </form>
        <div class="page" id="pageContent-search">
            <ul class="search-history-list">
                {% for history in search_history %}
                    <li class="history-item">
                        <a class="history-link" href="{{ url_for('view.view_history_detail', timestamp=history.timestamp) }}">
                            <span class="history-index">{{ loop.index }}.</span>
                            <span class="history-text">{{ history.search_text }}</span>
                            <span class="history-timestamp">{{ history.timestamp|datetime }}</span>
                            <button class="history-delete-btn" data-record-id="{{ history.id }}">삭제</button>
                        </a>
                </li>
                {% endfor %}
            </ul>
        </div>
        <script src="{{ url_for('static', filename='js/mypage.js') }}"></script>
</body>
</html>

web/templates/result.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>결과 페이지</title>
    <link rel="stylesheet" href={{url_for('static',filename='css/result.css')}}>
</head>
<body>
    <a href="{{ url_for('view.main') }}">
        <img src="{{ url_for('static', filename='logo.png') }}" alt="logo">
    </a>
    
    <!-- 로딩 화면 -->
    <div id="loadingContainer">
        <div class="loading"></div>
        <p id="loadingText">로딩 중</p>
        <p>결과가 나오기까지 대략 5분 정도 소요됩니다.</p>
    </div>
    <!-- 결과 화면 (처음에는 숨겨져 있음z) -->
    <div id="results" style="display: none;">
        <h3>인공지능 결과</h3>
        <p>결과: <span id="translationResult">{{ translated_text }}</span></p>
        <p>결과: <span id="imgCatResult">{{ img_cat }}</span></p>
        <img id="imageResult" src="" alt="이미지 결과">
        <button onclick="document.location.href='main'" id="backToSearchButton">검색 페이지로 돌아가기</button>
    </div>
    <script src="{{ url_for('static', filename='js/result.js') }}"></script>
</body>
</html>